# Generated by Django 5.0.6 on 2024-07-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_rename_producto_productos_remove_dvds_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvds',
            name='tipo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
